create table if not exists public.departmental_pharmacy_indent (
  id bigint generated by default as identity primary key,
  indent_no text unique,
  timestamp timestamp without time zone default now(),
  requested_by text,
  indent_scope text default 'departmental',
  request_source text default 'departmental',
  floor text,
  ward text,
  room text,
  ward_location text,
  category text,
  remarks text,
  purpose text,
  request_types text,
  medicines text,
  investigations text,
  investigation_advice text,
  status text default 'pending',
  planned1 timestamp without time zone,
  actual1 timestamp without time zone,
  planned2 timestamp without time zone,
  actual2 timestamp without time zone,
  approved_by text,
  approved_at timestamp without time zone,
  rejected_at timestamp without time zone,
  updated_at timestamp without time zone default now(),
  slip_image text,
  slip_image_url text,
  created_at timestamp without time zone default now()
);

create or replace function public.set_departmental_pharmacy_indent_no()
returns trigger
language plpgsql
as $$
declare
  next_number bigint;
begin
  if new.indent_no is not null and length(trim(new.indent_no)) > 0 then
    return new;
  end if;

  select coalesce(max(nullif(regexp_replace(indent_no, '[^0-9]', '', 'g'), '')::bigint), 0) + 1
    into next_number
  from public.departmental_pharmacy_indent;

  new.indent_no := 'DPI-' || lpad(next_number::text, 5, '0');
  return new;
end;
$$;

drop trigger if exists trg_set_departmental_pharmacy_indent_no on public.departmental_pharmacy_indent;

create trigger trg_set_departmental_pharmacy_indent_no
before insert on public.departmental_pharmacy_indent
for each row
execute function public.set_departmental_pharmacy_indent_no();

create or replace function public.touch_departmental_pharmacy_indent_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_touch_departmental_pharmacy_indent_updated_at on public.departmental_pharmacy_indent;

create trigger trg_touch_departmental_pharmacy_indent_updated_at
before update on public.departmental_pharmacy_indent
for each row
execute function public.touch_departmental_pharmacy_indent_updated_at();
