-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.all_floor_bed (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  timestamp timestamp with time zone NOT NULL DEFAULT now(),
  serial_no text,
  floor text,
  ward text,
  room text,
  bed text,
  status text,
  CONSTRAINT all_floor_bed_pkey PRIMARY KEY (id)
);
CREATE TABLE public.all_staff (
  timestamp timestamp with time zone NOT NULL DEFAULT now(),
  name text,
  phone_number text,
  email text,
  designation text,
  department text,
  id bigint NOT NULL DEFAULT nextval('all_staff_id_seq'::regclass),
  CONSTRAINT all_staff_pkey PRIMARY KEY (id)
);
CREATE TABLE public.category (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  name text NOT NULL,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT category_pkey PRIMARY KEY (id)
);
CREATE TABLE public.departmental_pharmacy_indent (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  indent_no text NOT NULL UNIQUE,
  timestamp timestamp with time zone DEFAULT now(),
  requested_by text NOT NULL,
  request_source text DEFAULT 'departmental'::text,
  floor text,
  ward text,
  room text,
  ward_location text,
  category text,
  remarks text,
  request_types jsonb,
  medicines jsonb,
  investigations jsonb,
  investigation_advice jsonb,
  status text DEFAULT 'pending'::text,
  planned1 timestamp with time zone,
  actual1 timestamp with time zone,
  planned2 timestamp with time zone,
  actual2 timestamp with time zone,
  approved_by text,
  approved_at timestamp with time zone,
  rejected_at timestamp with time zone,
  updated_at timestamp with time zone DEFAULT now(),
  slip_image text,
  slip_image_url text,
  indent_scope text,
  CONSTRAINT departmental_pharmacy_indent_pkey PRIMARY KEY (id)
);
CREATE TABLE public.discharge (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  timestamp timestamp without time zone NOT NULL,
  discharge_number text,
  admission_no text,
  patient_name text,
  department text,
  consultant_name text,
  staff_name text,
  remark text,
  planned1 timestamp without time zone,
  actual1 timestamp without time zone,
  delay1 text,
  rmo_status text,
  rmo_name text,
  summary_report_image text,
  summary_report_image_name text,
  planned2 timestamp without time zone,
  actual2 timestamp without time zone,
  delay2 text,
  work_file text,
  planned3 timestamp without time zone,
  actual3 timestamp without time zone,
  delay3 text,
  concern_dept text,
  planned4 timestamp without time zone,
  actual4 timestamp without time zone,
  delay4 text,
  concern_authority_work_file text,
  planned5 timestamp without time zone,
  actual5 timestamp without time zone,
  delay5 text,
  bill_status text,
  bill_image text,
  category text,
  CONSTRAINT discharge_pkey PRIMARY KEY (id)
);
CREATE TABLE public.doctors (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  timestamp timestamp with time zone NOT NULL DEFAULT now(),
  name text,
  phone_number text,
  email text,
  designation text,
  department text,
  CONSTRAINT doctors_pkey PRIMARY KEY (id)
);
CREATE TABLE public.dressing (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  timestamp timestamp without time zone NOT NULL,
  admission_number text,
  ipd_number text,
  patient_name text,
  task_no text,
  patient_location text,
  ward_type text,
  room text,
  bed_no text,
  planned1 timestamp without time zone,
  actual1 timestamp without time zone,
  remarks text,
  status text,
  submitted_by text,
  CONSTRAINT dressing_pkey PRIMARY KEY (id)
);
CREATE TABLE public.investigation (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  timestamp timestamp with time zone NOT NULL DEFAULT now(),
  type text,
  name text,
  price text,
  CONSTRAINT investigation_pkey PRIMARY KEY (id)
);
CREATE TABLE public.ipd_admissions (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  timestamp timestamp without time zone NOT NULL,
  admission_no text UNIQUE,
  patient_name text,
  father_husband_name text,
  age text,
  gender text,
  date_of_birth text,
  phone_no text,
  whatsapp_no text,
  email_id text,
  house_no_street text,
  area_colony text,
  landmark text,
  state text,
  city text,
  pincode text,
  country text,
  department text,
  refer_by_dr text,
  consultant_dr text,
  pat_category text,
  patient_case text,
  medical_surgical text,
  health_card_no text,
  adm_purpose text,
  location_status text,
  ward_no text,
  room_no text,
  bed_no text,
  bed_location text,
  ward_type text,
  room text,
  bed_tariff text,
  kin_name text,
  kin_relation text,
  kin_mobile_no text,
  advance_amount text,
  dr_visit_tariff text,
  package_name text,
  pkg_amount text,
  exp_tariff text,
  other_services text,
  vip_details text,
  religion text,
  marital_status text,
  attempt text,
  remarks text,
  planned1 timestamp without time zone,
  actual1 timestamp without time zone,
  delay text,
  ipd_number text NOT NULL DEFAULT get_next_ipd_number() UNIQUE,
  status text,
  floor text,
  staff_name text,
  diagnosis text,
  time_in_ward text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ipd_admissions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.lab (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  timestamp timestamp without time zone NOT NULL,
  admission_no text,
  lab_no text,
  patient_name text,
  phone_no text,
  father_husband_name text,
  age text,
  gender text,
  reason_for_visit text,
  bed_no text,
  location text,
  ward_type text,
  room text,
  department text,
  priority text,
  category text,
  pathology_tests jsonb,
  radiology_type text,
  radiology_tests jsonb,
  remarks text,
  status text,
  consultant_dr text,
  refer_by_dr text,
  planned1 text,
  actual1 text,
  delay1 text,
  payment_status text,
  bill_image_url text,
  planned2 text,
  actual2 text,
  delay2 text,
  report_url text,
  planned3 timestamp without time zone,
  actual3 timestamp without time zone,
  delay3 text,
  lab_report_remarks text,
  ipd_number text,
  actual4 timestamp without time zone,
  receive_sample text,
  planned4 timestamp without time zone,
  CONSTRAINT lab_pkey PRIMARY KEY (id)
);
CREATE TABLE public.leave (
  id integer NOT NULL DEFAULT nextval('leave_id_seq'::regclass),
  staff_name text NOT NULL,
  staff_type text NOT NULL CHECK (staff_type = ANY (ARRAY['nurse'::text, 'rmo'::text, 'ot'::text])),
  leave_date date NOT NULL DEFAULT CURRENT_DATE,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT leave_pkey PRIMARY KEY (id)
);
CREATE TABLE public.master (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  department text,
  nurse_task text,
  rmo_task text,
  CONSTRAINT master_pkey PRIMARY KEY (id)
);
CREATE TABLE public.medicine (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  timestamp timestamp with time zone NOT NULL DEFAULT now(),
  medicine_name text,
  price text,
  CONSTRAINT medicine_pkey PRIMARY KEY (id)
);
CREATE TABLE public.nurse_assign_task (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  timestamp timestamp without time zone NOT NULL,
  task_no text,
  Ipd_number text,
  patient_name text,
  patient_location text,
  ward_type text,
  room text,
  bed_no text,
  shift text,
  assign_nurse text,
  reminder text,
  start_date date,
  task text,
  planned1 timestamp without time zone,
  actual1 timestamp without time zone,
  staff text,
  ot_number text,
  status text,
  check_up text,
  submitted_by text,
  delegated_from text,
  CONSTRAINT nurse_assign_task_pkey PRIMARY KEY (id)
);
CREATE TABLE public.ot_information (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  timestamp timestamp without time zone NOT NULL,
  ot_number text,
  ipd_number text,
  patient_name text,
  patient_location text,
  ward_type text,
  room text,
  bed_no text,
  planned1 timestamp without time zone,
  actual1 timestamp without time zone,
  ot_date date,
  ot_time text,
  ot_description text,
  doctor text,
  rmo text,
  planned2 timestamp without time zone,
  actual2 timestamp without time zone,
  ot_staff text,
  status text,
  remark text,
  actual3 timestamp without time zone,
  assign_nurse text,
  submitted_by text,
  CONSTRAINT ot_information_pkey PRIMARY KEY (id)
);
CREATE TABLE public.patient_admission (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  timestamp timestamp without time zone NOT NULL,
  admission_no text UNIQUE,
  patient_name text,
  phone_no text,
  attender_name text,
  attender_mobile_no text,
  reason_for_visit text,
  date_of_birth text,
  age text,
  gender text,
  status text,
  planned1 text,
  actual1 text,
  delay text,
  department text,
  planned2 timestamp without time zone,
  actual2 timestamp without time zone,
  delay2 text,
  ipd_number text,
  submitted_by text,
  CONSTRAINT patient_admission_pkey PRIMARY KEY (id)
);
CREATE TABLE public.patient_deletion_log (
  id bigint NOT NULL DEFAULT nextval('patient_deletion_log_id_seq'::regclass),
  ipd_number text,
  admission_no text,
  patient_name text,
  deleted_by text NOT NULL,
  deleted_at timestamp with time zone DEFAULT now(),
  deletion_summary jsonb,
  CONSTRAINT patient_deletion_log_pkey PRIMARY KEY (id)
);
CREATE TABLE public.pharmacy (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  timestamp timestamp without time zone NOT NULL,
  indent_no text UNIQUE,
  admission_number text,
  ipd_number text,
  staff_name text,
  consultant_name text,
  patient_name text,
  uhid_number text,
  age text,
  gender text,
  ward_location text,
  category text,
  room text,
  diagnosis text,
  request_types text,
  medicines text,
  investigations text,
  investigation_advice text,
  status text DEFAULT 'pending'::text,
  delay text,
  planned1 timestamp without time zone,
  actual1 timestamp without time zone,
  approved_by text,
  slip_image text,
  planned2 timestamp without time zone,
  actual2 timestamp without time zone,
  delay2 text,
  CONSTRAINT pharmacy_pkey PRIMARY KEY (id)
);
CREATE TABLE public.pre_defined_task (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  task text,
  staff text,
  status text,
  CONSTRAINT pre_defined_task_pkey PRIMARY KEY (id)
);
CREATE TABLE public.rmo_assign_task (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  timestamp timestamp without time zone NOT NULL,
  task_no text UNIQUE,
  ipd_number text,
  patient_name text,
  patient_location text,
  ward_type text,
  room text,
  bed_no text,
  shift text,
  assign_rmo text,
  reminder text,
  start_date date,
  task text,
  planned1 timestamp without time zone,
  actual1 timestamp without time zone,
  ot_information text,
  status text,
  submitted_by text,
  CONSTRAINT rmo_assign_task_pkey PRIMARY KEY (id)
);
CREATE TABLE public.roster (
  id integer NOT NULL DEFAULT nextval('roster_id_seq'::regclass),
  timestamp timestamp with time zone DEFAULT now(),
  shift character varying NOT NULL CHECK (shift::text = ANY (ARRAY['Shift A'::character varying, 'Shift B'::character varying, 'Shift C'::character varying]::text[])),
  male_general_ward text,
  female_general_ward text,
  icu text,
  hdu text,
  private_ward text,
  nicu text,
  created_at timestamp with time zone DEFAULT now(),
  start_date date,
  picu text,
  general_ward_5th_floor text,
  CONSTRAINT roster_pkey PRIMARY KEY (id)
);
CREATE TABLE public.surgical_data (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  ipd_number text,
  patient_name text,
  surgery_time text,
  surgery_date date,
  planned1 timestamp without time zone,
  actual1 timestamp without time zone,
  CONSTRAINT surgical_data_pkey PRIMARY KEY (id)
);
CREATE TABLE public.trigger_debug_log (
  id integer NOT NULL DEFAULT nextval('trigger_debug_log_id_seq'::regclass),
  message text,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT trigger_debug_log_pkey PRIMARY KEY (id)
);
CREATE TABLE public.users (
  timestamp timestamp with time zone NOT NULL DEFAULT now(),
  user_name text,
  password text,
  role text,
  phone_no text,
  email text,
  pages text,
  name text,
  profile_image text,
  id bigint NOT NULL DEFAULT nextval('users_id_seq'::regclass),
  CONSTRAINT users_pkey PRIMARY KEY (id)
);
CREATE TABLE public.ward_config (
  id integer NOT NULL DEFAULT nextval('ward_config_id_seq'::regclass),
  ward_name text UNIQUE,
  roster_column text,
  CONSTRAINT ward_config_pkey PRIMARY KEY (id)
);